sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
install:
  - composer install
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
script:
  - make tests
